apiVersion: v1alpha1
kind: Setting
metadata:
  name: ai-cover-settings
spec:
  forms:
    # --- 组 1: 全局设置 ---
    - group: master-settings
      label: 全局设置
      formSchema:
        - $formkit: textarea
          name: models
          key: models
          id: models
          label: 可用模型列表
          placeholder: "一行一个模型，格式为：平台标识符,显示名称,模型ID"
          help: "例如：tongyi,通义万相V1,wanx-v1"
          value: |
            tongyi,通义万相 V1,wanx-v1
            siliconflow,Stable Diffusion XL,stable-diffusion-xl
            modelscope,FLUX.1-Krea-dev,black-forest-labs/FLUX.1-Krea-dev

    # --- 组 2: AI 平台统一设置 ---
    - group: ai-platform-settings
      label: AI 平台设置
      formSchema:
        # 使用 $el: h3 作为分组标题，让界面更清晰
        - $el: h3
          children: "通义万相 (Tongyi)"
        - $formkit: text
          name: tongyiApiKey # 使用带前缀的字段名
          key: tongyiApiKey
          id: tongyiApiKey
          label: API-KEY
          placeholder: "请输入您的阿里云百炼 API-KEY"
          help: "用于调用通义万相文生图服务的凭证。"
        
        - $el: h3
          children: "硅基流动 (SiliconFlow)"
        - $formkit: text
          name: siliconflowApiKey # 使用带前缀的字段名
          key: siliconflowApiKey
          id: siliconflowApiKey
          label: API-Key
          placeholder: "请输入您的硅基流动 API-Key"
        
        - $el: h3
          children: "魔塔 (ModelScope)"
        - $formkit: text
          name: modelscopeApiKey # 使用带前缀的字段名
          key: modelscopeApiKey
          id: modelscopeApiKey
          label: MODELSCOPE_SDK_TOKEN
          placeholder: "请输入您的魔塔 API Token (MODELSCOPE_SDK_TOKEN)"
          help: "用于调用魔塔文生图服务的凭证。可通过 AIGC 模型页面获取。"

    # --- 组 3: Alist 设置 (保持独立) ---
    - group: alist-settings
      label: Alist 设置
      formSchema:
        - $formkit: text
          name: alistUrl
          key: alistUrl
          id: alistUrl
          label: Alist 服务器地址
          placeholder: "例如: http://192.168.1.10:5244"
        - $formkit: text
          name: alistUsername
          key: alistUsername
          id: alistUsername
          label: Alist 用户名
        - $formkit: password
          name: alistPassword
          key: alistPassword
          id: alistPassword
          label: Alist 密码
        - $formkit: text
          name: alistUploadPath
          key: alistUploadPath
          id: alistUploadPath
          label: 图片上传路径
          placeholder: "例如: /uploads/covers"

